import type { ExtensionManifest } from '@core/extension-manifest.types';

const manifest: ExtensionManifest = {
  name: 'knowledge-agent',
  version: '1.0.0',
  displayName: 'Knowledge Agent',
  description: 'Knowledge base with markdown notes, pgvector RAG, graph viewer, and DeepAgent runtime.',
  author: '',
  engines: {
    foundation: '>=1.0.0',
    node: '>=18.0.0',
  },
  contributes: {
    routes: [
      { method: 'POST', path: 'ka/notes' },
      { method: 'GET', path: 'ka/notes' },
      { method: 'GET', path: 'ka/notes/:id' },
      { method: 'GET', path: 'ka/notes/:id/backlinks' },
      { method: 'PATCH', path: 'ka/notes/:id' },
      { method: 'DELETE', path: 'ka/notes/:id' },
      { method: 'GET', path: 'ka/graph' },
      { method: 'POST', path: 'ka/agent-configs' },
      { method: 'GET', path: 'ka/agent-configs' },
      { method: 'GET', path: 'ka/agent-configs/:id' },
      { method: 'PATCH', path: 'ka/agent-configs/:id' },
      { method: 'DELETE', path: 'ka/agent-configs/:id' },
      { method: 'POST', path: 'ka/model-providers' },
      { method: 'GET', path: 'ka/model-providers' },
      { method: 'GET', path: 'ka/model-providers/:id' },
      { method: 'PATCH', path: 'ka/model-providers/:id' },
      { method: 'DELETE', path: 'ka/model-providers/:id' },
      { method: 'POST', path: 'ka/models' },
      { method: 'GET', path: 'ka/models' },
      { method: 'GET', path: 'ka/models/active' },
      { method: 'GET', path: 'ka/models/:id' },
      { method: 'PATCH', path: 'ka/models/:id' },
      { method: 'DELETE', path: 'ka/models/:id' },
      { method: 'POST', path: 'ka/mcp-servers' },
      { method: 'GET', path: 'ka/mcp-servers' },
      { method: 'GET', path: 'ka/mcp-servers/:id' },
      { method: 'PATCH', path: 'ka/mcp-servers/:id' },
      { method: 'DELETE', path: 'ka/mcp-servers/:id' },
      { method: 'POST', path: 'ka/chat/sessions' },
      { method: 'GET', path: 'ka/chat/sessions' },
      { method: 'GET', path: 'ka/chat/sessions/:id' },
      { method: 'PATCH', path: 'ka/chat/sessions/:id' },
      { method: 'DELETE', path: 'ka/chat/sessions/:id' },
      { method: 'POST', path: 'ka/chat/sessions/:sessionId/message' },
    ],
    entities: [
      { name: 'Note', table: 'ext_ka_notes' },
      { name: 'NoteLink', table: 'ext_ka_note_links' },
      { name: 'AgentConfig', table: 'ext_ka_agent_configs' },
      { name: 'ChatSession', table: 'ext_ka_chat_sessions' },
      { name: 'ModelProvider', table: 'ext_ka_model_providers' },
      { name: 'Model', table: 'ext_ka_models' },
      { name: 'McpServer', table: 'ext_ka_mcp_servers' },
    ],
    seeds: true,
    config: [
      'KA_EMBEDDING_DIM',
      'KA_EMBEDDING_MODEL',
      'KA_OLLAMA_BASE_URL',
      'KA_SANDBOX_ENGINE',
      'KA_LOCAL_MCP_URL',
      'OPENROUTER_API_KEY',
    ],
    menuItems: [],
    permissions: [],
  },
};

export default manifest;
export { manifest };