/** @type {import('tailwindcss').Config} */
const path = require('node:path');

/*
 * Auto-generated by scripts/sync-assets.js
 * Colors synced from apps/front/assets/css/tailwind.css (DaisyUI theme)
 */
module.exports = {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  presets: [require('tailwindcss-preset-email')],
  content: [
    path.resolve(__dirname, 'src/modules/communications/mail/mail-templates/emails') + '/*.hbs',
    path.resolve(__dirname, 'src/modules/communications/mail/mail-templates/layouts') + '/*.hbs',
  ],
  theme: {
    extend: {
      colors: {
        // Synced from frontend DaisyUI theme
        primary: {
          50:  '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2e1065',
        },
        secondary: {
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
        },
        accent: {
          500: '#10b981',
          600: '#059669',
        },
        neutral: {
          100: '#f3f4f6',
          200: '#e5e7eb',
          500: '#6b7280',
          700: '#374151',
        },
      },
    },
  },
  mode: 'jit',
  plugins: [],
};
