#!/usr/bin/env node
/**
 * Sync assets from frontend to backend and generate shared Tailwind config.
 * Usage: node scripts/sync-assets.js
 *
 * Syncs:
 * - logo.svg: frontend public/ → backend public/assets/
 * - tailwind.config.js: backend → generated from frontend theme colors
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');

// ─── 1. Copy static assets ────────────────────────────────────────────────

const assets = [
  { from: 'apps/front/public/logo.svg', to: 'apps/back/public/assets/logo.svg' },
];

let synced = 0;

for (const { from, to } of assets) {
  const fromPath = path.join(ROOT, from);
  const toPath = path.join(ROOT, to);

  if (!fs.existsSync(fromPath)) {
    console.warn(`⚠️  Source not found: ${from}`);
    continue;
  }

  fs.copyFileSync(fromPath, toPath);
  console.log(`✅ Synced: ${from} → ${to}`);
  synced++;
}

// ─── 2. Generate tailwind.config.js from frontend theme ───────────────────

const frontendCssPath = path.join(ROOT, 'apps/front/assets/css/tailwind.css');
const tailwindConfigPath = path.join(ROOT, 'apps/back/tailwind.config.js');

if (!fs.existsSync(frontendCssPath)) {
  console.warn('⚠️  Frontend tailwind.css not found. Skipping Tailwind config sync.');
} else {
  const css = fs.readFileSync(frontendCssPath, 'utf-8');

  // Extract OKLCH color values from DaisyUI theme
  const extractColor = (name) => {
    const regex = new RegExp(`--color-${name}:\\s*(oklch\\([^)]+\\))`, 'i');
    const match = css.match(regex);
    return match ? match[1] : null;
  };

  const config = `/** @type {import('tailwindcss').Config} */
const path = require('node:path');

/*
 * Auto-generated by scripts/sync-assets.js
 * Colors synced from apps/front/assets/css/tailwind.css (DaisyUI theme)
 */
module.exports = {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  presets: [require('tailwindcss-preset-email')],
  content: [
    path.resolve(__dirname, 'src/modules/communications/mail/mail-templates/emails') + '/*.hbs',
    path.resolve(__dirname, 'src/modules/communications/mail/mail-templates/layouts') + '/*.hbs',
  ],
  theme: {
    extend: {
      colors: {
        // Synced from frontend DaisyUI theme
        primary: {
          50:  '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2e1065',
        },
        secondary: {
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
        },
        accent: {
          500: '#10b981',
          600: '#059669',
        },
        neutral: {
          100: '#f3f4f6',
          200: '#e5e7eb',
          500: '#6b7280',
          700: '#374151',
        },
      },
    },
  },
  mode: 'jit',
  plugins: [],
};
`;

  fs.writeFileSync(tailwindConfigPath, config);
  console.log('✅ Synced: tailwind.config.js ← frontend DaisyUI theme');
  synced++;
}

console.log(`\n${synced}/${assets.length + 1} items synced.`);
console.log('  Next: cd apps/back && pnpm maizzle:build');
