#!/usr/bin/env node
/**
 * spec-list-endpoints.ts — CLI that lists ALL endpoints in the app:
 * - Spec-engine generated (from YAML)
 * - Traditional NestJS controllers (from code)
 *
 * For each endpoint shows:
 * - HTTP method + path
 * - Guards (jwt, public, deny-all)
 * - Roles (admin, user, etc)
 * - Source (spec-engine YAML file or traditional controller file)
 * - Validation (DTO class-validator decorators or YAML validation rules)
 *
 * Usage:
 *   node src/core/spec-engine/spec-list-endpoints.ts [--json] [--verbose]
 *
 * Works WITHOUT the app running — reads YAML + source code.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// js-yaml from pnpm store
let yaml;
try {
  yaml = require('js-yaml');
} catch {
  const pnpmBase = path.resolve(process.cwd(), '../../node_modules/.pnpm');
  const jsYamlDir = fs
    .readdirSync(pnpmBase)
    .find((d) => d.startsWith('js-yaml@'));
  if (!jsYamlDir) {
    console.error('js-yaml not found.');
    process.exit(2);
  }
  yaml = require(path.join(pnpmBase, jsYamlDir, 'node_modules/js-yaml'));
}

const verbose =
  process.argv.includes('--verbose') || process.argv.includes('-v');
const asJson = process.argv.includes('--json');

const srcDir = path.resolve(process.cwd(), 'src');
const extensionsDir = path.join(srcDir, 'extensions');
const customDir = path.join(srcDir, 'custom');

// ─── Collect spec-engine endpoints (from YAML) ──────────────────────────

function collectSpecEndpoints() {
  const endpoints = [];

  // Search both extensions/ and custom/ for spec YAML files
  const searchDirs = [extensionsDir, customDir].filter((d) => fs.existsSync(d));

  for (const searchDir of searchDirs) {
    const isCustom = searchDir === customDir;

    for (const ext of fs.readdirSync(searchDir)) {
      const extDir = path.join(searchDir, ext);
      if (!fs.statSync(extDir).isDirectory()) continue;

      const specFiles = fs
        .readdirSync(extDir)
        .filter((f) => f.endsWith('.spec.yaml'))
        .map((f) => path.join(extDir, f));

      for (const file of specFiles) {
        try {
          const content = fs.readFileSync(file, 'utf-8');
          const spec = yaml.load(content);
          const resources = spec.resources || [spec];
          const extName = spec.name || ext;

          for (const resource of resources) {
            const rName = resource.name || extName;
            const table = resource.table || `ext_${ext}_${rName}`;
            const perms = resource.permissions || {};

            // CRUD endpoints (auto-generated by controller-factory)
            const crudOps = [
              {
                method: 'GET',
                path: `/${rName}`,
                action: 'list',
                roles: perms.list,
              },
              {
                method: 'GET',
                path: `/${rName}/:id`,
                action: 'read',
                roles: perms.read,
              },
              {
                method: 'POST',
                path: `/${rName}`,
                action: 'create',
                roles: perms.create,
              },
              {
                method: 'PATCH',
                path: `/${rName}/:id`,
                action: 'update',
                roles: perms.update,
              },
              {
                method: 'DELETE',
                path: `/${rName}/:id`,
                action: 'delete',
                roles: perms.delete,
              },
            ];

            for (const op of crudOps) {
              const roles = Array.isArray(op.roles) ? op.roles : [];
              const guardKind =
                roles.length === 0
                  ? 'deny-all'
                  : roles.includes('public')
                    ? 'public'
                    : 'jwt';

              // Field validations
              const validations = [];
              for (const field of resource.fields || []) {
                const v = field.validation;
                if (v) {
                  validations.push({
                    field: field.name,
                    type: field.type,
                    required: !!field.required,
                    min: v.min,
                    max: v.max,
                    pattern: v.pattern,
                    enum: field.enum,
                    ref: field.ref,
                  });
                } else if (field.required) {
                  validations.push({
                    field: field.name,
                    type: field.type,
                    required: true,
                    enum: field.enum,
                    ref: field.ref,
                  });
                }
              }

              endpoints.push({
                source: isCustom ? 'custom' : 'spec-engine',
                extension: extName,
                resource: rName,
                table,
                specFile: path.basename(file),
                method: op.method,
                path: `/api/v1${op.path}`,
                operation: op.action,
                guard: guardKind,
                roles,
                rowLevel: perms.rowLevel ? Object.keys(perms.rowLevel) : [],
                hooks: resource.hooks ? Object.keys(resource.hooks) : [],
                validations,
              });
            }

            // Action endpoints (custom non-CRUD)
            for (const action of resource.actions || []) {
              endpoints.push({
                source: isCustom ? 'custom' : 'spec-engine',
                extension: extName,
                resource: rName,
                table,
                specFile: path.basename(file),
                method: action.method || 'GET',
                path: `/api/v1/${rName}${action.path || '/'}`,
                operation: `action:${action.name}`,
                guard: 'jwt',
                roles: action.auth
                  ? action.auth.list || action.auth.update || []
                  : [],
                rowLevel: [],
                hooks: [],
                validations: [],
                actionName: action.name,
                handler: action.handler,
              });
            }

            // Webhook endpoints (inbound)
            for (const webhook of resource.webhooks || []) {
              endpoints.push({
                source: isCustom ? 'custom' : 'spec-engine',
                extension: extName,
                resource: rName,
                specFile: path.basename(file),
                method: 'POST',
                path: `/api/v1/${rName}/webhooks/${webhook.path || webhook.name}`,
                operation: `webhook:${webhook.name}`,
                guard: webhook.auth || 'none',
                roles: [],
                rowLevel: [],
                hooks: [],
                validations: [],
                webhookName: webhook.name,
              });
            }
          }
        } catch (err) {
          // skip parse errors
        }
      }
    }
  }

  return endpoints;
}

// ─── Collect traditional NestJS endpoints (from source code) ─────────────

function collectTraditionalEndpoints() {
  const endpoints = [];

  // Find all .controller.ts files
  const controllerFiles = execSync(
    `find ${srcDir} -name "*.controller.ts" -not -path "*__tests__*" -not -path "*node_modules*"`,
    { encoding: 'utf-8' },
  )
    .trim()
    .split('\n')
    .filter(Boolean);

  for (const file of controllerFiles) {
    try {
      const content = fs.readFileSync(file, 'utf-8');

      // Extract @Controller path
      let basePath = '';
      const ctrlMatch = content.match(
        /@Controller\s*\(\s*{?\s*(?:path:\s*)?['"`]([^'"`]+)['"`]/,
      );
      if (ctrlMatch) basePath = ctrlMatch[1];
      else {
        const simpleMatch = content.match(
          /@Controller\s*\(\s*['"`]([^'"`]+)['"`]/,
        );
        if (simpleMatch) basePath = simpleMatch[1];
        else if (content.match(/@Controller\s*\(\s*\)/)) basePath = '';
      }

      // Extract version
      let version = '1';
      const versionMatch = content.match(
        /@Controller\s*\(\s*{[^}]*version:\s*['"`](\d+)['"`]/,
      );
      if (versionMatch) version = versionMatch[1];

      // Extract @Roles at class level
      let classRoles = [];
      const classRolesMatch = content.match(/@Roles\s*\(\s*([^)]+)\s*\)/);
      if (classRolesMatch) {
        classRoles = classRolesMatch[1]
          .split(',')
          .map((r) => r.trim().replace(/RoleEnum\./g, ''))
          .filter(Boolean);
      }

      // Extract @UseGuards at class level
      let classGuards = [];
      const classGuardsMatch = content.match(/@UseGuards\s*\(\s*([^)]+)\s*\)/);
      if (classGuardsMatch) {
        classGuards = classGuardsMatch[1]
          .split(',')
          .map((g) => g.trim())
          .filter(Boolean);
      }

      // Extract method-level endpoints
      // Pattern: @Get|@Post|@Patch|@Delete|@Put followed by optional path
      const methodRegex =
        /@(Get|Post|Patch|Delete|Put)\s*\(\s*['"`]?([^'"`\)]*)['"`]?\s*\)/g;
      let match;

      while ((match = methodRegex.exec(content)) !== null) {
        const httpMethod = match[1].toUpperCase();
        const methodPath = match[2] || '';

        // Find @Roles and @UseGuards near this method (within 5 lines before)
        const lineStart = content.lastIndexOf('\n', match.index);
        const contextBefore = content.substring(
          Math.max(0, lineStart - 500),
          match.index,
        );

        let methodRoles = classRoles;
        const methodRolesMatch = contextBefore.match(
          /@Roles\s*\(\s*([^)]+)\s*\)/,
        );
        if (methodRolesMatch) {
          methodRoles = methodRolesMatch[1]
            .split(',')
            .map((r) => r.trim().replace(/RoleEnum\./g, ''))
            .filter(Boolean);
        }

        let methodGuards = classGuards;
        const methodGuardsMatch = contextBefore.match(
          /@UseGuards\s*\(\s*([^)]+)\s*\)/,
        );
        if (methodGuardsMatch) {
          methodGuards = methodGuardsMatch[1]
            .split(',')
            .map((g) => g.trim())
            .filter(Boolean);
        }

        // Build full path
        const fullPath = `/api${version ? '/v' + version : ''}/${basePath}${
          methodPath ? '/' + methodPath : ''
        }`;

        // Find DTO validations (look for @Body + class name, then find DTO file)
        const dtoMatch = content
          .substring(match.index, match.index + 1000)
          .match(/@Body\s*\(\s*\)?\s*(\w+Dto|\w+Request)/);

        let validations = [];
        if (dtoMatch) {
          const dtoName = dtoMatch[1];
          // Try to find the DTO file
          const dir = path.dirname(file);
          const dtoFiles = execSync(
            `find ${srcDir} -name "${dtoName}*" -o -name "*.dto.ts" | head -20`,
            { encoding: 'utf-8' },
          )
            .trim()
            .split('\n')
            .filter(Boolean);

          for (const dtoFile of dtoFiles) {
            try {
              const dtoContent = fs.readFileSync(dtoFile, 'utf-8');
              if (
                dtoContent.includes(dtoName) ||
                path.basename(dtoFile).includes(dtoName.toLowerCase())
              ) {
                // Extract validators
                const validators = dtoContent.match(
                  /@(Is\w+|Min\w+|Max\w+|Length|Matches)\s*\(\s*([^)]*)\s*\)/g,
                );
                if (validators) {
                  validations = validators.map((v) =>
                    v.replace(/\s+/g, ' ').trim(),
                  );
                }
                break;
              }
            } catch {
              // skip
            }
          }
        }

        endpoints.push({
          source: 'traditional',
          controllerFile: path.relative(process.cwd(), file),
          method: httpMethod,
          path: fullPath,
          guard:
            methodGuards.includes('JwtAuthGuard') ||
            methodGuards.includes("AuthGuard('jwt')")
              ? 'jwt'
              : methodGuards.length > 0
                ? methodGuards.join(',')
                : 'none',
          roles: methodRoles,
          validations,
        });
      }
    } catch {
      // skip unreadable files
    }
  }

  return endpoints;
}

// ─── Main ────────────────────────────────────────────────────────────────

const specEndpoints = collectSpecEndpoints();
const traditionalEndpoints = collectTraditionalEndpoints();
const allEndpoints = [...specEndpoints, ...traditionalEndpoints];

if (asJson) {
  console.log(JSON.stringify(allEndpoints, null, 2));
  process.exit(0);
}

// Human-readable output
console.log(`\n🔌 Foundation — ${allEndpoints.length} endpoints\n`);
console.log('─'.repeat(80));

// Group by source
const specCount = specEndpoints.length;
const tradCount = traditionalEndpoints.length;
console.log(
  `\nSpec-engine: ${specCount} endpoints | Traditional: ${tradCount} endpoints\n`,
);

// Group by path prefix
const byPrefix = {};
for (const ep of allEndpoints) {
  const prefix = ep.path.split('/').slice(0, 3).join('/');
  if (!byPrefix[prefix]) byPrefix[prefix] = [];
  byPrefix[prefix].push(ep);
}

for (const [prefix, eps] of Object.entries(byPrefix).sort()) {
  console.log(`\n${prefix}/`);
  for (const ep of eps) {
    const methodPad = ep.method.padEnd(6);
    const guardStr = ep.guard ? `[${ep.guard}]` : '';
    const rolesStr = ep.roles.length > 0 ? `roles: ${ep.roles.join(',')}` : '';
    const sourceStr =
      ep.source === 'spec-engine'
        ? `📦 ${ep.extension}/${ep.specFile}`
        : `📝 ${ep.controllerFile}`;

    console.log(`  ${methodPad} ${ep.path.padEnd(45)} ${guardStr} ${rolesStr}`);

    if (verbose) {
      if (ep.source === 'spec-engine') {
        if (ep.resource)
          console.log(`         resource: ${ep.resource} (${ep.table})`);
        if (ep.operation) console.log(`         operation: ${ep.operation}`);
        if (ep.rowLevel.length > 0)
          console.log(`         rowLevel: ${ep.rowLevel.join(', ')}`);
        if (ep.hooks.length > 0)
          console.log(`         hooks: ${ep.hooks.join(', ')}`);
        if (ep.actionName)
          console.log(
            `         action: ${ep.actionName} → handler: ${ep.handler}`,
          );
        if (ep.validations.length > 0) {
          console.log(`         validations:`);
          for (const v of ep.validations) {
            const parts = [];
            if (v.required) parts.push('required');
            if (v.min !== undefined) parts.push(`min:${v.min}`);
            if (v.max !== undefined) parts.push(`max:${v.max}`);
            if (v.pattern) parts.push(`pattern:${v.pattern}`);
            if (v.enum) parts.push(`enum:[${v.enum.join(',')}]`);
            if (v.ref) parts.push(`ref:${v.ref}`);
            console.log(
              `           ${v.field} (${v.type}): ${parts.join(', ')}`,
            );
          }
        }
      } else {
        if (ep.validations.length > 0) {
          console.log(`         validations: ${ep.validations.length} rules`);
          for (const v of ep.validations.slice(0, 5)) {
            console.log(`           ${v}`);
          }
        }
      }
      console.log(`         source: ${sourceStr}`);
    }
  }
}

console.log('\n' + '─'.repeat(80));
console.log(`\nTotal: ${allEndpoints.length} endpoints`);
console.log(`  Spec-engine: ${specCount}`);
console.log(`  Traditional: ${tradCount}`);
