import { MigrationInterface, QueryRunner } from 'typeorm';

// Migration generated by pnpm migration:generate, manually edited to use RENAME instead of DROP/CREATE
export class RenameCmsTablesToExtPrefix1777544607618
  implements MigrationInterface
{
  name = 'RenameCmsTablesToExtPrefix1777544607618';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Rename enum type for page.section column (was created as page_section_enum)
    await queryRunner.query(
      `ALTER TYPE "public"."page_section_enum" RENAME TO "ext_cms_page_section_enum"`,
    );

    // Rename entity tables
    await queryRunner.query(`ALTER TABLE "page" RENAME TO "ext_cms_page"`);
    await queryRunner.query(
      `ALTER TABLE "blog_post" RENAME TO "ext_cms_blog_post"`,
    );
    await queryRunner.query(
      `ALTER TABLE "blog_category" RENAME TO "ext_cms_blog_category"`,
    );
    await queryRunner.query(
      `ALTER TABLE "post_tag" RENAME TO "ext_cms_post_tag"`,
    );
    await queryRunner.query(
      `ALTER TABLE "seo_metadata" RENAME TO "ext_cms_seo_metadata"`,
    );

    // Rename join tables
    await queryRunner.query(
      `ALTER TABLE "blog_post_tag" RENAME TO "ext_cms_blog_post_tag"`,
    );
    await queryRunner.query(
      `ALTER TABLE "blog_category_tag" RENAME TO "ext_cms_blog_category_tag"`,
    );

    // Unrelated schema change detected by TypeORM: add category column to translation
    await queryRunner.query(
      `ALTER TABLE "translation" ADD "category" character varying`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_ea73dc8ba4e3cd20823a585eb0" ON "translation" ("category")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverse translation.category changes
    await queryRunner.query(
      `DROP INDEX "public"."IDX_ea73dc8ba4e3cd20823a585eb0"`,
    );
    await queryRunner.query(`ALTER TABLE "translation" DROP COLUMN "category"`);

    // Rename join tables back
    await queryRunner.query(
      `ALTER TABLE "ext_cms_blog_category_tag" RENAME TO "blog_category_tag"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ext_cms_blog_post_tag" RENAME TO "blog_post_tag"`,
    );

    // Rename entity tables back
    await queryRunner.query(
      `ALTER TABLE "ext_cms_seo_metadata" RENAME TO "seo_metadata"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ext_cms_post_tag" RENAME TO "post_tag"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ext_cms_blog_category" RENAME TO "blog_category"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ext_cms_blog_post" RENAME TO "blog_post"`,
    );
    await queryRunner.query(`ALTER TABLE "ext_cms_page" RENAME TO "page"`);

    // Rename enum type back
    await queryRunner.query(
      `ALTER TYPE "public"."ext_cms_page_section_enum" RENAME TO "page_section_enum"`,
    );
  }
}
